# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ee3098233b6d2dfd9d382d0fb63406733ec2d4ba75459e480713c39df2c38d098bb3fa381cbb8f4698ddb777eed339f73e45fd50028b1a8266fb8bc73b418b8

test:
  secret_key_base: 8de6750b7198380ec0d058e94e90d3ad5c46f354aaddae437900481793a68f3e10a5b4c29fb791726cb23849dc7d80c2a381c679b0cca32685623680aa8651ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
